# A rebuild on the current slim tag ships openssl/libssl3t64 >= 3.5.4-1~deb13u2
# (OLYM-7625, OLYM-7626). Left as a floating tag so future base-image security
# updates arrive automatically on each rebuild.
FROM python:3.14-slim

# Pinned to a uv release bundling astral-tokio-tar >= 0.6.1 (OLYM-7622); uv
# 0.11.11+ carries the fix. A version tag (over :latest) keeps builds reproducible.
COPY --from=ghcr.io/astral-sh/uv:0.11.25 /uv /uvx /bin/

WORKDIR /app

# Which cloud-platform variant to build (aws | gcp). Selects the
# optional-dependency extra so each image ships only that platform's LLM SDK.
# The runtime backend is chosen separately via the LLM_PROVIDER env var
# (aws->bedrock, gcp->vertex).
ARG CLOUD=aws

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project --extra ${CLOUD}
COPY src/ src/
RUN uv sync --frozen --no-dev --extra ${CLOUD}

# Licensing artifacts: this project's own license, plus the per-platform NOTICE
# and verbatim third-party license texts for everything bundled in the image
# (generated by scripts/gen_licenses.py from the built image). uv ships as a
# copied binary rather than a pip package, so its license is added from the
# shared source.
COPY LICENSE ./
COPY licensing/${CLOUD}/NOTICE ./NOTICE
COPY licensing/${CLOUD}/LICENSES/ LICENSES/
COPY licensing/uv/ LICENSES/uv/

CMD [".venv/bin/llm-worker"]
