# A rebuild on the current slim tag ships openssl/libssl3t64 >= 3.5.4-1~deb13u2
# (OLYM-7625, OLYM-7626). Left as a floating tag so future base-image security
# updates arrive automatically on each rebuild. Both stages must name the same
# tag: the virtualenv copied out of the builder records an absolute interpreter
# path, so it is only valid if the runtime stage has that interpreter too.
FROM python:3.14-slim AS builder

# uv builds the virtualenv and then stays behind in this stage. It is a large
# statically-linked Rust binary, so anything compiled into it resolves as a
# dependency of whatever image ships it — keeping it out of the runtime layer is
# the point of this split (AO-1069). Held on the 0.11 line because
# [build-system] requires uv_build <0.12. A version tag (over :latest) keeps
# builds reproducible.
COPY --from=ghcr.io/astral-sh/uv:0.11.33 /uv /uvx /bin/

WORKDIR /app

# Which cloud-platform variant to build (aws | gcp | azure). Selects the
# optional-dependency extra so each image ships only that platform's LLM SDK.
# The runtime backend is chosen separately via the LLM_PROVIDER env var
# (aws->bedrock, gcp->vertex, azure->foundry).
ARG CLOUD=aws

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project --extra ${CLOUD}
COPY src/ src/
RUN uv sync --frozen --no-dev --extra ${CLOUD}


FROM python:3.14-slim

WORKDIR /app

# uv installs the project itself in editable mode, so the venv resolves the
# package through src/ — both have to come across for the console script to
# import.
COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app/src /app/src

# Licensing artifacts: this project's own license, plus the per-platform NOTICE
# and verbatim third-party license texts for everything bundled in the image
# (generated by scripts/gen_licenses.py from the built image). uv ships as a
# copied binary rather than a pip package, so its license is added from the
# shared source.
ARG CLOUD=aws
COPY LICENSE ./
COPY licensing/${CLOUD}/NOTICE ./NOTICE
COPY licensing/${CLOUD}/LICENSES/ LICENSES/
COPY licensing/uv/ LICENSES/uv/

CMD [".venv/bin/llm-worker"]
